# keep-server-alive.yml
name: Keep Server Alive

on:
  schedule:
    - cron: '*/7 * * * *'   # Every 7 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: |
          curl -m 60 \
            -H "x-github-internal: ${{ secrets.X_GITHUB_INTERNAL }}" \
            "${{ secrets.SERVER_URL }}/health"
